pipelines:
  branches:
    '{master}':
      - step:
          name: Build and Test
          image: thecodingmachine/php:7.4-v3-apache
          services:
            - mariadb
          caches:
            - composer
          script:
            - mv .env.pipeline .env
            - composer install
#            - php artisan migrate
#            - php artisan db:seed
            - ./vendor/bin/grumphp run
            - rm .env
      - step:
          name: Deploy to Staging
          deployment: Staging
          script:
            - pipe: atlassian/sftp-deploy:0.5.0
              variables:
                USER: $USER
                SERVER: $HOST
                REMOTE_PATH: '/var/www/vhosts/auth.beta.spidersmart.com/'
                PASSWORD: $PASSWORD
      - step:
          name: Deploy to Production
          trigger: manual
          deployment: Production
          script:
            - pipe: atlassian/sftp-deploy:0.5.0
              variables:
                USER: $USER
                SERVER: $HOST
                REMOTE_PATH: '/www/'
                PASSWORD: $PASSWORD

definitions:
  services:
    mariadb:
      image: mariadb:10
      environment:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_ROOT_PASSWORD: 'test'
