image: node:latest

before_script:
  - npm install

stages:
  - deploy

master:
  stage: deploy
  script:
    - ./node_modules/.bin/gulp build -production
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/order-analytics.git
    - git add public/*
    - git config --global user.email "eddy@beetechy.com"
    - git config --global user.name "Eddy"
    - git commit -m "adding generated css and js"
    - git push -f heroku HEAD:master
